### PR TITLE
Docker scripts and setup instructions

### PR DESCRIPTION
**Pull request by zarathustra323**
- Adds Docker convenience scripts and basic setup instructions. The `README` outlines the scripts that were added and the steps to install dependencies (as well as how to add/remove them).
- The `useNewUrlParser: true` option was added to the Mongoose connection config to remove a deprecation notice that the underlying `mongodb` driver was displaying.

### CODE REVIEW

**Comment by roadlittledawn** [comment]
this is great! i like the added .sh files so i don't have to constantly look up those commands. nice touch.

two questions:
* in [docker-compose.yaml](https://github.com/roadlittledawn/wtq-node/pull/1/files#diff-4e5e90c6228fd48698d074241c2ba760), how exactly does that command value `["start"]` work?
* how does that yarn workspace.sh work when adding/removing packages?

also, FWIW: i still saw what looked like deprecation warnings after running `docker-compose up`
    
    (node:38) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

**Comment by roadlittledawn** [comment]
and you've done me happy adding some documentation in the readme ;)

**Comment by zarathustra323** [comment]
> * in [docker-compose.yaml](https://github.com/roadlittledawn/wtq-node/pull/1/files#diff-4e5e90c6228fd48698d074241c2ba760), how exactly does that command value `["start"]` work?

The `command` value is literally the value that will be executed against the entrypoint. In this case, the entrypoint is `yarn`. When the container runs, it will execute `yarn start`. The array syntax is there to list each item of the command. It's just a preference thing. Per Docker's docs:

```
command
Override the default command.
`command: bundle exec thin -p 3000`

The command can also be a list, in a manner similar to dockerfile:
`command: ["bundle", "exec", "thin", "-p", "3000"]`
```

The result of `yarn start` is that the `gulp` command will run. This is due to it being defined as the `start` value under `scripts` within the `services/api/package.json` file. Because a `gulpfile.js` is also located in that folder, Gulp will use it to define and run its own tasks. In this case, it serves/watches the files in the `api` directory and performs linting (via eslint) on file save.

**Comment by zarathustra323** [comment]
> * how does that yarn workspace.sh work when adding/removing packages?

Yarn workspaces allow you to split a larger repository into smaller "packages" and "services" and is one way of managing a "monorepo" (along with Lerna). We probably didn't need to make this a monorepo (it probably doesn't need the complexity) but, oh well. :) 

The workspace `add` command will install the package _only_ for the selected service. In this case, the `wtq-node-api` service. It will place the the dependency in the `services/api/package.json` but Yarn will manage/install the dependencies globally for all services.

More on Yarn workspaces: https://yarnpkg.com/lang/en/docs/workspaces/
More on Lerna: https://lernajs.io/

**Comment by zarathustra323** [comment]
> (node:38) DeprecationWarning: collection.ensureIndex is deprecated. Use createIndexes instead.

This is a different dep notice than the one I addressed in the PR. The warning is being displayed by the underlying `mongodb` package that Mongoose uses, but Mongoose hasn't updated their code yet to address it. It can't be fixed until Mongoose updates their code and then we update our version of it. I haven't checked to see if they have a patch version that does this yet, though. They might.

**Comment by roadlittledawn** [comment]
**re: how ['start'] works**
ah okay. i was confused about that array syntax. that's some weird syntax to put each segment of a command into an array. but okay  ¯\_(ツ)_/¯ 

and thanks for additional info on what `yarn start` actually does. forgot exactly what gulp did (and i confused it in my head with guzzle), but it rings a bell now.

**re: yarn workspaces**
i remember chatting about that. how do i specify what package to install using that script though? what is the last line mean? is that `$a` a variable?

    workspace $@

**re: additional deprecation warning**
ah okay. something for me to try when that's released.

i'll tentatively approve and merge this. thanks!

**Comment by zarathustra323** [comment]
> **re: yarn workspaces**
> i remember chatting about that. how do i specify what package to install using that script though? what is the last line mean? is that `$a` a variable?

It's in the `README.md` as a part of this PR. ;) To add a package for the api service, run `scripts/workspace.sh wtq-node-api add [package-name]` where `[package-name]` is the npm package :) The `wtq-node-api` argument is required so that Yarn knows which workspace you're adding the package to. The reason it's named `wtq-node-api` is because that's the `name` specified in the `services/api/package.json` file.

Regarding the `$@`, that's syntax for "accept any input provided." In this case, it's accepting `add [package-name]`.

**Pull request merged**
